# compose file for local development
# update command_executor to "http://selenium:4444/wd/hub"
# for deployment executor is "http://selenium-hub:4444/wd/hub"
version: '3'
services:
  app:
    image: matthewcai/colin-scraper
    ports: 
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - selenium
    env_file:
      - .env
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
