apiVersion: v1
kind: ConfigMap
metadata: 
  name: colin-scraper-config
data:
  STAFF_USERNAME: "mcai"
  STAFF_PASSWORD:  "Qq1133557799"
  ORACLE_DB_USERNAME: "readonly"
  ORACLE_DB_PASSWORD: "t3mpt3mp"
  ORACLE_DB_DSN: "cprd.world"
  DATE_RANGE_START: "2002/01/01"
  DATE_RANGE_END: "2003/01/01"
  FINAL_END_DATE: "2023/01/05"
